### ISSUE TITLE
eslint issue

### ISSUE THREAD

**Issue by ORESoftware** [Terminux/react-csv-downloader#12]
I am getting this error...I am new to this app (taking over from someone else) and not sure what it's about

```
Failed to create a production build. Reason:
Module build failed: Error: /home/olegzandr/Documents/WebstormProjects/moover/portal/node_modules/eslint-config-airbnb-base/rules/imports.js:
        Configuration for rule "import/no-unresolved" is invalid:
        Value "data["0"].caseSensitive" has additional properties.

Referenced from: /home/olegzandr/Documents/WebstormProjects/moover/portal/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /home/olegzandr/Documents/WebstormProjects/moover/portal/src/modules/react-csv-downloader/.eslintrc
    at validateRuleOptions (/home/olegzandr/Documents/WebstormProjects/moover/portal/node_modules/eslint/lib/config/config-validator.js:115:15)
    at Object.keys.forEach.id (/home/olegzandr/Documents/WebstormProjects/moover/portal/node_modules/eslint/lib/config/config-validator.js:162:13)
    at Array.forEach (native)

```

do you have any any idea how I can fix this error?

**Comment by Shangyunliang** [comment]
me too, can you fix it ?
